name: Build and Tests

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '17.x'
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
    
  circular-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm install -g madge
      - run: madge src/App.ts -c
